### ISSUE TITLE
Many bugs and issues I have encountered.

### ISSUE THREAD

**Issue by bartman901** [Ryorama/Terrariamod#1]
Hello, I've got pretty interested in your mod and would like to help pointing out issues I have encountered during my gameplay.
I'm using newest build of the game, with new features. I aknowledge that it's meant to be for testing purpose and that bugs in that version are inevitable.

I will start with missing/bugged textures. Table's texture, furnace icon's texture dosn't work. I think cactus armor, pwnhammer. gold pickaxe, molten pickaxe, cobat sword and viled powder's icon will be changed as for now it looks like a bad quality png picture.
![2020-08-14_15h04_40](https://user-images.githubusercontent.com/69680002/90257514-901bb280-de47-11ea-82d0-4961bfba51b7.png)
Armor looks rather misplaced in slots, but looks cool on character.
![2020-08-14_15h03_42](https://user-images.githubusercontent.com/69680002/90257455-7d08e280-de47-11ea-90cf-58012ea82305.png)

Duplocate bug. When you place doors you don't loose them, and when you break them you get 2 doors. So it's like infinite door bug.

Music. When in certain places in underworld, overworld music starts playing.

Mobs: In my honest opinion mobs spawnrate is too low, especially in underworld. I know it's being developed but hell should be even more deadly. Also, I aknowledged that new mobs will change, but I would point out that demons are really small and it's really hard to see them in underworld. Even if I attack slimes they don't posses any threat unless I will intentionally walk at them.

Cave system. I'm aware it could be pointed out a lot of times in the past but cave system is...not what it should be. Looking at how fast it is to get from overworld to underworld clearly shows that. I hope you are working hard on solving that. After you would expand underground layer, something that would be rather easy to implement are underground houses with chest inside of it. Also, if underground layer will be expanded, ores such as gold or silver would spawn on lower levels. (Because as for now, I even sometimes see gold or silver on the surface!)

Overall issues. There are literally TOO MANY ores lying around. If their generation would be lowered by multiplier of 1/6 or 1/8, it would be much better. In my honest opinion, there is too much grass around. Very often there is floating grass over canyon/caves I hope bosses AI will be improved in the future as currently boss fights are pretty unsatisfying. Melee weapons should have usage time like orginal minecraft or terraria, I hope you are planning to change that soon.

That's all I had to say for now. I keep my fingers crossed for your project and can't wait for further updates!

**Comment by Ryorama** [comment]
Hello, thanks for this massive bug and suggestion report, like seriously. Most of these bugs are known and will be fixed. The underworld being to high in the world is something I have been facing for a while, with Minecraft's hight limit, it's impossible to make the world taller without removing the limit which in order to do so, the entire engine has to be rewritten from the ground up. The boss AI is planned to be improved in the last beta of v1.1 which will also include a lot of new visual changes and fixes and overall a better Terraria feel to the mod. Again, thanks for writing this and hope you have a great day!
