### ISSUE TITLE
Server startup fails: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/EntityRenderer

### ISSUE THREAD

**Issue by aetepi** [Ryorama/Terrariamod#2]
Mod starts successfully in single player, but cannot start on new server with the mod installed (no other mods).  Browsed the Discord and comments and didn't see any mention of this.
Error appears to be a client-only class that doesn't exist within the Forge server:
[17:04:27] [modloading-worker-1/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to register automatic subscribers. ModID: trewrite, class kmerrill285.trewrite.Trewrite
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/entity/EntityRenderer

Mod File: Terrariamod+v1.1+Beta+3+Bugfix+2.jar 
Forge server: forge-1.14.4-28.2.23.jar
Java: Oracle 1.8.0_251

Server startup output attached along with crash_report generated
[terraria_server_output.txt](https://github.com/Ryorama/Terrariamod/files/5374145/terraria_server_output.txt)
[crash_report.txt](https://github.com/Ryorama/Terrariamod/files/5374137/crash_report.txt)

**Comment by Ryorama** [comment]
Hello, thanks for reporting this issue. It is actually a known issue, but currently has no fix. It seems to be a bug where the server can’t load one of Minecraft’s classes, but it’s really strange. I will keep you up to date on the issue once a fix has been found.

**Comment by Ryorama** [comment]
Will be fixed in latest build. I will now close this issue.
