### ISSUE TITLE
New chunks sometimes cause items to stop registering and game to not save

### ISSUE THREAD

**Issue by Aranduran** [Ryorama/Terrariamod#5]
When I generate new chunks, there seems to be a chance for all of the terraria items to stop functioning. Sometimes I can still use a sword or pickaxe when this happens, and when that is the case, I see a corresponding item in my minecraft inventory hotbar when I press 'm'. Further, if I keep playing after this happens, I find that nothing is saved. If I hold an item that doesn't have a minecraft item that corresponds with it then I will have an empty hand (so if I select my sword, but I was holding some other item when it first happened, I have no sword).

This seems to be caused most frequently by trying to generate new chunks. I find if I walk in certain directions it seems to happen more frequently, but it eventually happens whichever direction I take.

I can't help wondering, since it seems to involve generating new chunks, whether or not it is connected to #3

**Comment by Ryorama** [comment]
Hey! I've decided to discontinue the 1.14.4 version and focus on my fabric 1.17 port. This bug will no longer persist in that version as it used an entirely different generation system. Thanks for the report though!
